spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mariadb://localhost:3306/immobile
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: studiomedico.gruppo1.java8@gmail.com
    password: csrenoniyugittmc
    properties:
      mail:
        smtp:
          auth: None
          starttls:
            enable: true
authframework:
  jwt:
    hskey: KTlgvPcXbnLoYl6b5Ma1oG294dGoZ+fyxBqJiBjQjVo=
    audience: testaudience
    token-ttl: 86400000
