spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/immobile
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: None
          starttls:
            enable: true
authframework:
  jwt:
    hskey: 
    audience: testaudience
    token-ttl: 86400000
